; PlatformIO Project Configuration File for LILYGO T-Micro32 Plus
;
; For more options, visit:
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = t-micro32-plus
; src_dir = firmware/src
; lib_dir = firmware/lib
; include_dir = firmware/include
; test_dir = firmware/test
; data_dir = firmware/data

[base_config]
platform = espressif32@3.4
framework = arduino
monitor_speed = 921600
monitor_flags = 
	--eol=CRLF
	--echo
	--filter=esp32_exception_decoder
upload_speed = 921600
lib_deps =
build_flags =
    -DMONITOR_SPEED=921600

[env:t-micro32-plus]
extends = base_config
board = esp32dev
board_build.partitions = default_ffat.csv  ; Change to a suitable partition scheme if needed
board_build.flash_mode = dio         ; Optimal flash mode for ESP32
board_build.flash_size = 8MB         ; Sets the flash size to 8MB
board_build.psram = true             ; Enables 2MB of PSRAM
upload_speed = 921600                ; Speed for faster uploads
monitor_speed = 115200               ; Serial monitor speed
; upload_port = /dev/ttyUSB0           ; Update this for your specific port

; Optional Libraries (install as dependencies)
lib_deps = 
    ${base_config.lib_deps}
    ; Add your libraries here
    ; e.g., adafruit/Adafruit BME280 Library @ ^2.0.2
    ; Uncomment and add if needed

build_flags = 
    ${base_config.build_flags}
    -DBOARD_HAS_PSRAM             ; Enables PSRAM support in code
    -mfix-esp32-psram-cache-issue ; Fixes known PSRAM issue on ESP32
    -DLED_BUILTIN=2               ; Set the onboard LED pin
    -DARDUINOJSON_ENABLE_PROGMEM=1 ; Optional JSON library optimization for PROGMEM

    ; Copy other build flags from the og smartknob platformio.ini file i.e.: Pin Mapping, sensor speeds

extra_scripts =  
; Custom Serial Stream Settings
; Commented out cause not using the default USB CDC from the S3 board
; build_flags = 
;     -DARDUINO_USB_CDC_ON_BOOT=1 
;     -DUSBCON=1

; For further partitioning adjustments, reference:
; https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/partition-tables.html
